package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.function.Supplier;

import org.littletonrobotics.junction.AutoLogOutput;
import org.littletonrobotics.junction.Logger;
import org.photonvision.PhotonUtils;

import com.ctre.phoenix6.Orchestra;
import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.commands.PathfindingCommand;
import com.pathplanner.lib.config.ModuleConfig;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import com.pathplanner.lib.path.PathConstraints;
import com.pathplanner.lib.pathfinding.LocalADStar;
import com.pathplanner.lib.pathfinding.Pathfinding;

import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Pose3d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Transform2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.kinematics.SwerveModuleState;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.system.plant.DCMotor;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.networktables.StructArrayPublisher;
import edu.wpi.first.networktables.StructPublisher;
import edu.wpi.first.units.measure.Angle;
import edu.wpi.first.units.measure.AngularVelocity;
import edu.wpi.first.units.measure.Distance;
import edu.wpi.first.units.measure.LinearVelocity;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.CommandScheduler;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.Constants;
import frc.robot.FieldLayout;
import frc.robot.Robot;
import frc.robot.Util.GeomUtil;
import frc.robot.Util.CustomSwerveRequests.FieldCentricCircularOrbit;
import frc.robot.Util.CustomSwerveRequests.FieldCentricGoToPoint;
import frc.robot.Util.CustomSwerveRequests.FieldCentricRestrictedRadius;
import frc.robot.Util.CustomSwerveRequests.FieldCentricXAxisAlign;
import frc.robot.Util.CustomSwerveRequests.FieldCentricYAxisAlign;
import frc.robot.Util.MapleSimSwerveDrivetrain;
import frc.robot.Util.RobotBumpSim;
import frc.robot.commands.auton.PointToPointAutons.AutonWaypoints;
import frc.robot.commands.auton.PointToPointAutons.WaypointSet;
import frc.robot.generated.TunerConstants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    private Orchestra orchestra = new Orchestra();

    private RobotBumpSim robotBumpSim;

    private Optional<SwerveRequest> currentRequest = Optional.empty();

    private Rotation2d initialRotation = new Rotation2d();
    private Pose2d initialPose = new Pose2d();

    private MapleSimSwerveDrivetrain mapleSimSwerveDrivetrain = null;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    private final Field2d field = new Field2d();

    private final StructPublisher<Pose2d> testPosePublisher = NetworkTableInstance.getDefault()
            .getStructTopic("Test Pose", Pose2d.struct).publish();

    private final StructArrayPublisher<Pose2d> autonPathPublisher = NetworkTableInstance.getDefault()
            .getStructArrayTopic("P2P Auton Publisher", Pose2d.struct).publish();

    private Pose2d[] autonPathArray = new Pose2d[0];

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    // Swerve Requests to apply to Robot
    private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();

    private final SwerveRequest.FieldCentric driveRequest = new SwerveRequest.FieldCentric()
            .withDeadband(Constants.linDeadband)
            .withRotationalDeadband(Constants.angDeadband)
            .withDriveRequestType(DriveRequestType.Velocity);

    private final SwerveRequest.FieldCentricFacingAngle gotoAngleRequest = new SwerveRequest.FieldCentricFacingAngle()
            .withRotationalDeadband(Constants.angDeadband)
            .withHeadingPID(10, 0, 0)
            .withDriveRequestType(DriveRequestType.Velocity);

    private final FieldCentricCircularOrbit orbitRequest = new FieldCentricCircularOrbit()
            .withRadiusCorrectionPID(3, 0, 0)
            .withHeadingPID(10, 0, 0)
            .withDriveRequestType(DriveRequestType.Velocity);

    private final FieldCentricGoToPoint goToRequest = new FieldCentricGoToPoint()
            .withHeadingPID(10, 0, 0)
            .withTranslationPID(4, 0, 0);

    private final FieldCentricRestrictedRadius orbitRestricteRadiusRequest = new FieldCentricRestrictedRadius()
            .withRadiusCorrectionPID(3, 0, 0)
            .withHeadingPID(10, 0, 0)
            .withDriveRequestType(DriveRequestType.Velocity);

    private final FieldCentricXAxisAlign xAxisAlignRequest = new FieldCentricXAxisAlign()
            .withDriveRequestType(DriveRequestType.Velocity)
            .withHeadingPID(10, 0, 0)
            .withXAxisCorrectionPID(4, 0, 0);

    private final FieldCentricYAxisAlign yAxisAlignRequest = new FieldCentricYAxisAlign()
            .withDriveRequestType(DriveRequestType.Velocity)
            .withHeadingPID(10, 0, 0)
            .withYAxisCorrectionPID(4, 0, 0);

    private final SwerveRequest.SwerveDriveBrake brakeRequest = new SwerveRequest.SwerveDriveBrake();
    private final SwerveRequest.Idle idleRequest = new SwerveRequest.Idle();

    // Pathplanner
    @SuppressWarnings("unused")
    private RobotConfig config = new RobotConfig(
            32,
            0.1,
            new ModuleConfig(
                    Inches.of(1.75).in(Meters),
                    TunerConstants.kSpeedAt12Volts.in(MetersPerSecond),
                    0.1,
                    DCMotor.getKrakenX60(1),
                    60,
                    1),
            Inches.of(25).in(Meters));

    /*
     * SysId routine for characterizing translation. This is used to find PID gains
     * for the drive motors.
     */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> setControl(m_translationCharacterization.withVolts(output)),
                    null,
                    this));

    /*
     * SysId routine for characterizing steer. This is used to find PID gains for
     * the steer motors.
     */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(7), // Use dynamic voltage of 7 V
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdSteer_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    volts -> setControl(m_steerCharacterization.withVolts(volts)),
                    null,
                    this));

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle
     * HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on
     * importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    /* This is in radians per second², but SysId only supports "volts per second" */
                    Volts.of(Math.PI / 6).per(Second),
                    /* This is in radians per second, but SysId only supports "volts" */
                    Volts.of(Math.PI),
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdRotation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> {
                        /* output is actually radians per second, but SysId only supports "volts" */
                        setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                        /* also log the requested output for SysId */
                        SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
                    },
                    null,
                    this));

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
     * @param modules             Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, MapleSimSwerveDrivetrain.regulateModuleConstantsForSimulation(modules));
        if (Utils.isSimulation()) {
            startSimThread();
        }

        configurePathFinder();
        // Configure AutoBuilder last
        configureAutoBuilder();
        configureOrchestra();
        configureTelemetry();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, odometryUpdateFrequency, MapleSimSwerveDrivetrain.regulateModuleConstantsForSimulation(modules));
        if (Utils.isSimulation()) {
            startSimThread();
        }

        configurePathFinder();
        // Configure AutoBuilder last
        configureAutoBuilder();
        configureOrchestra();
        configureTelemetry();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve
     *                                  drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz
     *                                  on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry
     *                                  calculation
     *                                  in the form [x, y, theta]ᵀ, with units in
     *                                  meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision
     *                                  calculation
     *                                  in the form [x, y, theta]ᵀ, with units in
     *                                  meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            Matrix<N3, N1> odometryStandardDeviation,
            Matrix<N3, N1> visionStandardDeviation,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation,
                MapleSimSwerveDrivetrain.regulateModuleConstantsForSimulation(modules));
        if (Utils.isSimulation()) {
            startSimThread();
        }

        configurePathFinder();
        // Configure AutoBuilder last
        configureAutoBuilder();
        configureOrchestra();
        configureTelemetry();
    }

    /**
     * Stores the current request before calling parent's copy of the method
     * 
     * @param request Swerve drive control request
     */
    @Override
    public void setControl(SwerveRequest request) {
        this.currentRequest = Optional.of(request);
        super.setControl(request);
    }

    /**
     * Returns a command that applies the specified control request to this swerve
     * drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test for Translation in the given direction
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdTranslationQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineTranslation.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test for Translation in the given direction
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdTranslationDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineTranslation.dynamic(direction);
    }

    /**
     * Runs the SysId Quasistatic test for steer in the given direction
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdSteerQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineSteer.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test for steer in the given direction
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdSteerDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineSteer.dynamic(direction);
    }

    /**
     * Runs the SysId Quasistatic test for rotation in the given direction
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdRotationQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineRotation.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test for rotation in the given direction
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdRotationDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineRotation.dynamic(direction);
    }

    @SuppressWarnings("unchecked")
    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        robotBumpSim =
            new RobotBumpSim(getModuleLocations());

        mapleSimSwerveDrivetrain = new MapleSimSwerveDrivetrain(
                Seconds.of(kSimLoopPeriod),
                Pounds.of(109.3),
                Constants.robotLength,
                Constants.robotWidth,
                DCMotor.getKrakenX60Foc(1),
                DCMotor.getFalcon500(1),
                1.2,
                getModuleLocations(),
                getPigeon2(),
                getModules(),
                TunerConstants.FrontLeft,
                TunerConstants.FrontRight,
                TunerConstants.BackLeft,
                TunerConstants.BackRight);
        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(mapleSimSwerveDrivetrain::update);
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision
     *                              camera.
     * @param timestampSeconds      The timestamp of the vision measurement in
     *                              seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters    The pose of the robot as measured by the
     *                                 vision camera.
     * @param timestampSeconds         The timestamp of the vision measurement in
     *                                 seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose
     *                                 measurement
     *                                 in the form [x, y, theta]ᵀ, with units in
     *                                 meters and radians.
     */
    @Override
    public void addVisionMeasurement(
            Pose2d visionRobotPoseMeters,
            double timestampSeconds,
            Matrix<N3, N1> visionMeasurementStdDevs) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds),
                visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is
     *         empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    private void configureAutoBuilder() {
        try {
            var config = RobotConfig.fromGUISettings();
            AutoBuilder.configure(
                    () -> getState().Pose, // Supplier of current robot pose
                    this::resetPose, // Consumer for seeding pose against auto
                    () -> getState().Speeds, // Supplier of current robot speeds
                    // Consumer of ChassisSpeeds and feedforwards to drive the robot
                    (speeds, feedforwards) -> setControl(
                            m_pathApplyRobotSpeeds.withSpeeds(ChassisSpeeds.discretize(speeds, 0.020))
                                    .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                                    .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())),
                    new PPHolonomicDriveController(
                            // PID constants for translation
                            new PIDConstants(13, 0, 0),
                            // PID constants for rotation
                            new PIDConstants(7, 0, 0)),
                    config,
                    // Assume the path needs to be flipped for Red vs Blue, this is normally the
                    // case
                    () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
                    this // Subsystem for requirements
            );
        } catch (Exception ex) {
            DriverStation.reportError("Failed to load PathPlanner config and configure AutoBuilder",
                    ex.getStackTrace());
        }
    }

    private void configurePathFinder() {
        Pathfinding.setPathfinder(new LocalADStar());
        CommandScheduler.getInstance().schedule(PathfindingCommand.warmupCommand());
    }

    private void configureOrchestra() {
        // for (int i = 0; i < 4; i ++){
        // TalonFX targetMotor = this.getModule(i).getDriveMotor();
        // orchestra.addInstrument(targetMotor);
        // targetMotor.getConfigurator().apply(new
        // AudioConfigs().withAllowMusicDurDisable(true));
        // }

        // orchestra.loadMusic("efn.chrp");
        // orchestra.play();
    }

    private void configureTelemetry() {
        SmartDashboard.setDefaultNumber("TestPoseX", 0);
        SmartDashboard.setDefaultNumber("TestPoseY", 0);
        SmartDashboard.setDefaultNumber("TestPoseR", 0);
    }

    @AutoLogOutput
    public Pose2d getPose2d() {
        if (Robot.isReal()){
            return getState().Pose;
        }else{
            return mapleSimSwerveDrivetrain.mapleSimDrive.getSimulatedDriveTrainPose();
        }
    }

    @AutoLogOutput
    public SwerveModuleState[] getModuleStates() {
        return getState().ModuleStates;
    }

    @AutoLogOutput
    public ChassisSpeeds getChassisSpeeds() {
        return getState().Speeds;
    }

    /**
     * Checks if the robot orientation is within tolerance of a target angle
     *
     * @param tolerance check tolerance
     * @return True if the robot is controlling orientation and is within tolerance
     *         of the target. False otherwise.
     */
    public boolean atTargetAngle(Angle tolerance) {
        return currentRequest.isPresent() &&
                currentRequest.get() == gotoAngleRequest &&
                MathUtil.isNear(
                        gotoAngleRequest.TargetDirection.getDegrees(),
                        getPose2d().getRotation().getDegrees(),
                        tolerance.in(Degrees));
    }

    @Override
    public void resetPose(Pose2d pose) {
        if (this.mapleSimSwerveDrivetrain != null) mapleSimSwerveDrivetrain.mapleSimDrive.setSimulationWorldPose(pose);
        Timer.delay(0.05); // wait for simulation to update
        super.resetPose(pose);
    }

    public Command getResetPoseCmd(Pose2d pose) {
        return this.runOnce(() -> resetPose(pose));
    }

    public Command getResetPoseCmd(Supplier<Pose2d> pose) {
        return this.runOnce(() -> resetPose(pose.get()));
    }

    public Command getResetPoseAllianceCmd(Pose2d pose){
        return this.runOnce(() -> {
            resetPose(FieldLayout.isRedAlliance() ? new Pose2d(pose.getTranslation(), pose.getRotation().rotateBy(Rotation2d.k180deg)) : pose);
        });
    }
    
    public Command getResetPoseAllianceCmd(Supplier<Pose2d> pose){
        return this.runOnce(() -> {
            resetPose(FieldLayout.isRedAlliance() ? new Pose2d(pose.get().getTranslation(), pose.get().getRotation().rotateBy(Rotation2d.k180deg)) : pose.get());
        });
    }

    public void updateDrawAutonPath(Pose2d[] points) {
        autonPathArray = points;
    }

    public Command drawAutonPathCmd(WaypointSet points) {
        return this.runOnce(() -> updateDrawAutonPath(points.getResolvedArray()));
    }

    public Command getPathFindCmd(Pose2d targetPose, PathConstraints constraints) {
        return AutoBuilder.pathfindToPoseFlipped(targetPose, constraints);
    }

    public Command getPathFindCmd(Pose2d targetPose, PathConstraints constraints, LinearVelocity endVelocity) {
        return AutoBuilder.pathfindToPoseFlipped(targetPose, constraints, endVelocity);
    }

    /**
     * Creates a command to drive the drivetrain at field-centric linear and
     * angular velocities
     * 
     * @param xVel target x velocity
     * @param yVel target y velocity
     * @param rVel target angular velocity
     * @return command to run at the target velocities
     */
    public Command getDriveCmd(
            Supplier<LinearVelocity> xVel,
            Supplier<LinearVelocity> yVel,
            Supplier<AngularVelocity> rVel) {

        // Drivetrain will execute this command periodically
        return applyRequest(
                () -> driveRequest
                        .withVelocityX(xVel.get())
                        .withVelocityY(yVel.get())
                        .withRotationalRate(rVel.get()));

    }

    /**
     * Creates a command to drive the drivetrain at field-centric linear velocities
     * and maintain a target field-centric angle
     * 
     * @param xVel   target x velocity
     * @param yVel   target y velocity
     * @param target target angle
     * @return new gotoAngle Cmd
     */
    public Command gotoAngleCmd(
            Supplier<LinearVelocity> xVel,
            Supplier<LinearVelocity> yVel,
            Rotation2d target) {

        return applyRequest(
                () -> gotoAngleRequest
                        .withVelocityX(xVel.get())
                        .withVelocityY(yVel.get())
                        .withTargetDirection(target));
    }

    /**
     * Creates a command to drive the drivetrain at field-centric linear velocities
     * and orient the robot toward a point on the field
     * 
     * @param xVel   target x velocity
     * @param yVel   target y velocity
     * @param target target point to point towards
     * @param offset offset angle for the orientation
     * @return new lookAtPoint command
     */
    public Command lookAtPointCmd(
            Supplier<LinearVelocity> xVel,
            Supplier<LinearVelocity> yVel,
            Translation2d target,
            Rotation2d offset) {
        return applyRequest(
                () -> gotoAngleRequest
                        .withVelocityX(xVel.get())
                        .withVelocityY(yVel.get())
                        .withTargetDirection(
                                getPose2d().getTranslation().minus(target).getAngle().plus(offset)))
                .withName("Look at Point Command");
    }

    public Command travelSetSpeedCmd(Supplier<LinearVelocity> xVel, Supplier<LinearVelocity> yVel,
            Rotation2d targetAngle) {
        return applyRequest(
                () -> gotoAngleRequest
                        .withVelocityX(xVel.get())
                        .withVelocityY(yVel.get())
                        .withTargetDirection(targetAngle))
                .withName("Travel Set Speed Command");
    }

    /**
     * Creates a command to drive the drivetrain at field-centric linear velocities
     * and orient the robot toward the center of the current alliance hub
     * 
     * @param xVel   target x velocity
     * @param yVel   target y velocity
     * @param offset offset angle for the orientation
     * @return new lookAtHub command
     */
    public Command lookAtHubCmd(
            Supplier<LinearVelocity> xVel,
            Supplier<LinearVelocity> yVel,
            Rotation2d offset) {

        return lookAtPointCmd(xVel, yVel, FieldLayout.Hub.getHubCenter(), offset);
    }

    public Command hubOrbitCommand(Supplier<LinearVelocity> travelVel, Rotation2d offset, Distance radius) {
        return applyRequest(() -> orbitRequest
                .withOrbitPoint(FieldLayout.Hub.getHubCenter())
                .withTravelVelocity(travelVel.get())
                .withRotationalOffset(offset)
                .withRadius(radius))
                .finallyDo(() -> applyRequest(() -> idleRequest))
                .withName("Hub Orbit Command");
    }

    public Command hubOrbitShakeCommand(Supplier<LinearVelocity> travelVel, Rotation2d offset, Rotation2d shakeAmplitude, Distance radius, Distance distTol, Rotation2d rotTol){
        return hubOrbitCommand(travelVel, offset, radius)
            .until(() -> FieldLayout.Hub.getHubDist(getPose2d().getTranslation()).isNear(radius, distTol) 
                && Math.abs(getPose2d().getRotation().relativeTo(orbitRequest.getTargetDirection()).getDegrees()) < rotTol.getDegrees())
            .andThen(

                new SequentialCommandGroup(
                    hubOrbitCommand(travelVel, offset.plus(shakeAmplitude), radius)
                    .withTimeout(0.1),
                    
                    hubOrbitCommand(travelVel, offset.minus(shakeAmplitude), radius)
                    .withTimeout(0.1)
                ).repeatedly()
            )
            .finallyDo(() -> applyRequest(() -> idleRequest))
            .withName("Hub Orbit Command");
    }

    public Command towerAlignCommand(Supplier<LinearVelocity> travelVel, Rotation2d offset, Translation2d PosOffset) {
        return applyRequest(() -> goToRequest
                .withTargetPoint(FieldLayout.Tower.getTowerCenter().plus(PosOffset))
                .withRotationalOffset(offset))
                .finallyDo(() -> applyRequest(() -> idleRequest))
                .withName("Tower Align Command");
    }

    public Command goToPointCmd(Supplier<Pose2d> targetPose, Distance tolerance) {
        return applyRequest(() -> goToRequest
                .withTargetPoint(targetPose.get().getTranslation())
                .withRotationalOffset(targetPose.get().getRotation()))
                .until(() -> Math.abs(PhotonUtils.getDistanceToPose(getPose2d(), targetPose.get())) <= tolerance
                        .in(Meters))
                .finallyDo(() -> applyRequest(() -> idleRequest));
    }

    public Command goToPointCmd(Supplier<Pose2d> targetPose) {
        return applyRequest(() -> goToRequest
                .withTargetPoint(targetPose.get().getTranslation())
                .withRotationalOffset(targetPose.get().getRotation()))
                .until(() -> Math.abs(PhotonUtils.getDistanceToPose(getPose2d(),
                        targetPose.get())) <= Constants.autonPointToPointTolerance.in(Meters))
                .finallyDo(() -> applyRequest(() -> idleRequest));
    }

    public Command goToPointNoFinishCmd(Pose2d targetPose) {
        return applyRequest(() -> goToRequest
                .withTargetPoint(targetPose.getTranslation())
                .withRotationalOffset(targetPose.getRotation()))
                .finallyDo(() -> applyRequest(() -> idleRequest));
    }

    public Command goToPointCruiseCmd(Supplier<Pose2d> targetPose, LinearVelocity velocity, Distance tolerance) {
        return applyRequest(
                () -> {
                    Pose2d currentPose = getPose2d();
                    Pose2d resolvedPose = targetPose.get();

                    double xDiff = resolvedPose.getX() - currentPose.getX();
                    double yDiff = resolvedPose.getY() - currentPose.getY();

                    double angle = Math.atan2(yDiff, xDiff);

                    double allianceFlip = FieldLayout.isRedAlliance() ? -1 : 1;

                    LinearVelocity vx = velocity.times(Math.cos(angle)).times(allianceFlip);
                    LinearVelocity vy = velocity.times(Math.sin(angle)).times(allianceFlip);

                    return gotoAngleRequest
                            .withVelocityX(vx)
                            .withVelocityY(vy)
                            .withTargetDirection(resolvedPose.getRotation());
                }).until(() -> PhotonUtils.getDistanceToPose(getPose2d(), targetPose.get()) <= tolerance.in(Meters));
    }

    public Command goToPointRotationCruiseCmd(Supplier<Pose2d> targetPose, LinearVelocity velocity, AngularVelocity rotationalVel, Distance distTol, Rotation2d rotTol) {
        return applyRequest(
                () -> {
                    Pose2d currentPose = getPose2d();
                    Pose2d resolvedPose = targetPose.get();

                    double xDiff = resolvedPose.getX() - currentPose.getX();
                    double yDiff = resolvedPose.getY() - currentPose.getY();

                    double angle = Math.atan2(yDiff, xDiff);

                    double allianceFlip = FieldLayout.isRedAlliance() ? -1 : 1;

                    LinearVelocity vx = velocity.times(Math.cos(angle)).times(allianceFlip);
                    LinearVelocity vy = velocity.times(Math.sin(angle)).times(allianceFlip);

                    

                    return driveRequest
                        .withVelocityX(vx)
                        .withVelocityY(vy)
                        .withRotationalRate(
                            getPose2d().getRotation().relativeTo(
                                targetPose.get().getRotation())
                            .getMeasure().abs(Degrees) <= rotTol.getDegrees() ? RotationsPerSecond.zero() : rotationalVel);
                }).until(() -> PhotonUtils.getDistanceToPose(getPose2d(), targetPose.get()) <= distTol.in(Meters));
    }

    public Command hubOrbitRestrictedRadiusCommand(Supplier<LinearVelocity> travelVel,
            Supplier<LinearVelocity> radialVelocity,
            Rotation2d offset, Distance maxRadius, Distance minRadius) {
        return applyRequest(() -> orbitRestricteRadiusRequest
                .withOrbitPoint(FieldLayout.Hub.getHubCenter())
                .withTravelVelocity(travelVel.get())
                .withRotationalOffset(offset)
                .withMaxRadius(maxRadius)
                .withMinRadius(minRadius)
                .withRadiusVelocity(radialVelocity.get()))
                .finallyDo(() -> applyRequest(() -> idleRequest))
                .withName("Hub Orbit Restricted Radius Command");
    }

    public Command passOrbitRestrictedRadiusCommand(Supplier<LinearVelocity> travelVel,
            Supplier<LinearVelocity> radialVelocity, Rotation2d offset, Distance maxRadius, Distance minRadius) {
        return applyRequest(() -> orbitRestricteRadiusRequest
                .withOrbitPoint(FieldLayout.getFeedPosition(() -> getPose2d()).getTranslation())
                .withTravelVelocity(travelVel.get())
                .withRotationalOffset(offset)
                .withMaxRadius(maxRadius)
                .withMinRadius(minRadius)
                .withRadiusVelocity(radialVelocity.get())
                .withUpdateTargetPose(() -> FieldLayout.getFeedPosition(this::getPose2d)))
                .finallyDo(() -> applyRequest(() -> idleRequest))
                .withName("Hub Orbit Restricted Radius Command");
    }

    public Command autoAimCommand(Supplier<LinearVelocity> travelVel, Supplier<LinearVelocity> radialVelocity,
            Rotation2d offset, Distance maxRadius, Distance minRadius) {
        return Commands.either(
                hubOrbitCommand(travelVel, offset, minRadius),
                passOrbitRestrictedRadiusCommand(travelVel, radialVelocity, offset, maxRadius, minRadius),
                () -> FieldLayout.inAllianceZone(this::getPose2d));
    }
    

    public Command xAxisAlignCmd(Supplier<LinearVelocity> travelVelX, Rotation2d targetRotation,
            Translation2d coordinate) {
        return applyRequest(() -> xAxisAlignRequest
                .withTravelVelocity(travelVelX.get())
                .withTargetDirection(targetRotation)
                .withXAxisCoordinate(coordinate)
                .withUpdateTargetPose(null))
                .finallyDo(() -> applyRequest(() -> idleRequest))
                .withName("X-Axis Align Command");
    }

    /**
     * 
     * @param travelVelX     The desired travel velocity. Positive is up and
     *                       negative is down. Sign must match direction to target
     *                       pose
     * @param targetPose     The desired pose to go to.
     * @param tolerance      The desired tolerance distance for the command to end
     * @param targetRotation Target rotation of the robot
     * @param coordinate     The coordinate axis the robot should align to.
     * @return
     */
    public Command xAxisAlignDistanceCmd(Supplier<LinearVelocity> travelVelX, Supplier<Pose2d> targetPose,
            Distance tolerance) {
        return applyRequest(() -> {
            return xAxisAlignRequest
                    .withTravelVelocity(travelVelX.get())
                    .withTargetDirection(targetPose.get().getRotation())
                    .withXAxisCoordinate(targetPose.get().getTranslation())
                    .withUpdateTargetPose(null);
        })
                .until(() -> Math.abs(PhotonUtils.getDistanceToPose(getPose2d(), targetPose.get())) <= tolerance
                        .in(Meters))
                .finallyDo(() -> applyRequest(() -> idleRequest))
                .withName("X-Axis Align Distance Command");
    }

    public Command yAxisAlignCmd(Supplier<LinearVelocity> travelVelY, Rotation2d targetRotation,
            Translation2d coordinate) {
        return applyRequest(() -> yAxisAlignRequest
                .withTravelVelocity(travelVelY.get())
                .withTargetDirection(targetRotation)
                .withYAxisCoordinate(coordinate))
                .finallyDo(() -> applyRequest(() -> idleRequest))
                .withName("Y-Axis Align Command");
    }

    /**
     * 
     * @param travelVelX     The desired travel velocity. Positive is up and
     *                       negative is down. Sign must match direction to target
     *                       pose
     * @param targetPose     The desired pose to go to.
     * @param tolerance      The desired tolerance distance for the command to end
     * @param targetRotation Target rotation of the robot
     * @param coordinate     The coordinate axis the robot should align to.
     * @return
     */
    public Command yAxisAlignDistanceCmd(Supplier<LinearVelocity> travelVelY, Supplier<Pose2d> targetPose,
            Distance tolerance) {
        return applyRequest(() -> {
            return yAxisAlignRequest
                    .withTravelVelocity(travelVelY.get())
                    .withTargetDirection(targetPose.get().getRotation())
                    .withYAxisCoordinate(targetPose.get().getTranslation())
                    .withUpdateTargetPose(null);
        })
        .until(() -> Math.abs(PhotonUtils.getDistanceToPose(getPose2d(), targetPose.get())) <= tolerance.in(Meters))
        .andThen(this.runOnce(() -> applyRequest(() -> idleRequest)))
        .withName("Y-Axis Align Distance Command");
    }

    public void initialRotationHelper(Rotation2d rotation) {
        initialRotation = rotation;
    }

    public void initialPoseHelper(Pose2d pose) {
        initialPose = pose;
    }

    public Pose2d getInitialPose() {
        return initialPose;
    }

    public Command hubBackAlignCmd(Supplier<LinearVelocity> travelVelY) {
        return applyRequest(() -> yAxisAlignRequest
                .withTravelVelocity(travelVelY.get())
                .withTargetDirection(initialRotation)
                // .withYAxisCoordinate(coordinate)
                .withUpdateTargetTranslation(() -> FieldLayout.Hub.getHubBackAlign(getPose2d())))
                .finallyDo(() -> applyRequest(() -> idleRequest))
                .withName("Hub Back Align Command");
    }

    public Command trenchAlignCmd(Supplier<LinearVelocity> travelVelX) {
        return applyRequest(() -> xAxisAlignRequest
                .withTravelVelocity(travelVelX.get())
                .withUpdateTargetPose(() -> FieldLayout.Trench.getNearestAllianceTrench(getPose2d(), Rotation2d.kZero)))
                .finallyDo(() -> applyRequest(() -> idleRequest))
                .withName("Trench Align Command");
    }

    public Command trenchAngleAlignCmd(Supplier<LinearVelocity> travelVelX, Rotation2d angleOffset) {
        return applyRequest(() -> xAxisAlignRequest
                .withTravelVelocity(travelVelX.get())
                .withUpdateTargetPose(() -> FieldLayout.Trench.getNearestAllianceTrench(getPose2d(), FieldLayout.getNearestRotation(getPose2d(), angleOffset))))
                .finallyDo(() -> applyRequest(() -> idleRequest))
                .withName("Trench Align Command");
    }

    public Command trenchPathAlignCmd(Translation2d targetPose) {
        return AutoBuilder.pathfindToPose(new Pose2d(targetPose, Rotation2d.kZero),
                new PathConstraints(TunerConstants.kSpeedAt12Volts, Constants.maxLinAccel, Constants.maxAngVel,
                        Constants.maxAngAccel));
    }

    public Translation2d calcTrenchPoint(Pose2d targetPoint) {
        double maxDistance = Constants.maxRobotTrenchDistance.in(Meters);
        var offset = targetPoint.minus(getPose2d());
        double xDistance = Math.abs(offset.getX());
        double yDistance = Math.abs(offset.getY());
        double testValue = 3;

        double shiftX = MathUtil.clamp((yDistance / (testValue * 2)) + ((xDistance - 0.3) / (testValue * 3)), 0, 1);
        double shiftY = MathUtil.clamp(yDistance / testValue, 0, 1);

        Pose2d shiftedPose = targetPoint
                .transformBy(GeomUtil.toTransform2d(-Math.copySign(shiftX * maxDistance, offset.getX()),
                        -Math.copySign(shiftY * maxDistance * 0.8, offset.getY())));

        return shiftedPose.getTranslation();
    }

    /**
     * Crosses the swerve modules in an X pattern
     * 
     * @return new Brake Command
     */
    public Command brakeCmd() {
        return applyRequest(() -> brakeRequest);
    }

    /**
     * Gets a robot Idle Command
     * 
     * @return new idle command
     */
    public Command idleCmd() {
        return applyRequest(() -> idleRequest);
    }

    @AutoLogOutput
    public String getCommandString() {
        return this.getCurrentCommand() == null ? "null" : this.getCurrentCommand().getName();
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply
         * it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts
         * mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is
         * disabled.
         * This ensures driving behavior doesn't change until an explicit disable event
         * occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                        allianceColor == Alliance.Red
                                ? kRedAlliancePerspectiveRotation
                                : kBlueAlliancePerspectiveRotation);
                m_hasAppliedOperatorPerspective = true;
            });
        }

        double testPoseX = SmartDashboard.getNumber("TestPoseX", 0);
        double testPoseY = SmartDashboard.getNumber("TestPoseY", 0);
        double testPoseR = SmartDashboard.getNumber("TestPoseR", 0);

        Pose2d testPose = new Pose2d(testPoseX, testPoseY, Rotation2d.fromDegrees(testPoseR));
        testPosePublisher.set(testPose);

        autonPathPublisher.set(autonPathArray);

        // SmartDashboard.putNumber("Operator Facing Mode",
        // this.getOperatorForwardDirection().getDegrees());
        SmartDashboard.putNumber("Distance From Hub",
                FieldLayout.Hub.getHubDist(getPose2d().getTranslation()).in(Meters));
        field.setRobotPose(getPose2d());
        SmartDashboard.putData("Field2d", field);

        SmartDashboard.putNumber("Orbit Target Direction", orbitRequest.getTargetDirection().getDegrees());  
    }

    @Override
    public void simulationPeriodic(){
        Logger.recordOutput("MapleSim Pose3d", mapleSimSwerveDrivetrain.getPose3d());
    }

}
